name: CICD_FLOW
on: 
  pull_request:
    types:
      - opened
  workflow_dispatch:
jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4.1.2
      - name: Install dependencies
        run: pip install -r app/requirements.txt
      - name: Run tests
        run: pytest
        
